version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5001:5001"  # Host port 5001 to container port 5001
    env_file:
      - ./backend/.env
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:5001  # Internal Docker network URL
    depends_on:
      - backend
